# $$\text{Tarea NLP ML AZ}$$

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ignoramos las comillas dobles quoting
dataset = pd.read_csv('./Restaurant_Reviews.tsv', sep='\t', quoting=3)

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

#limpieza
corpus = []
for i in range(dataset.shape[0]):
    review = re.sub('[^a-zA-Z]',' ',dataset.Review[i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

#back of word
from sklearn.feature_extraction.text import CountVectorizer 

cv = CountVectorizer(max_features=1200)
X = cv.fit_transform(corpus).toarray()
X.shape

y = dataset.iloc[:,1].values

[nltk_data] Downloading package stopwords to /home/alex/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
# dividimos en datos de entrenamiento y prueba
from  sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0,test_size=0.2)

In [4]:
# función de precisión de algoritmos
from sklearn.metrics import confusion_matrix 

def precision():
    y_pred = classifier.predict(X_test)
    
    cm = confusion_matrix(y_test,y_pred)
    print('Matriz de confusión:')
    print(cm)
    print('')
    Accuracy = (cm[0][0] + cm[1][1])/len(y_test)
    print(f'Accuracy: {round(Accuracy,2)}')
    Presicion = (cm[0][0])/(cm[0][0] + cm[1][0])
    print(f'Presición: {round(Presicion,2)}')
    Recall = (cm[0][0])/(cm[0][0] + cm[0][1])
    print(f'Recall: {round(Recall,2)}')
    F1Score = (2*Presicion*Recall)/(Presicion+Recall)
    print(f'F1 Score: {round(F1Score,2)}')

#### `Pregunta 1`
`Ejecuta los otros algoritmos de clasificación que elaboramos en la
Parte 3 - Clasificación, además del que ya he usado en esta última
clase de la sección.`

#### `Pregunta 2`
`Evalúa la eficacia de todos estos modelos. Intenta mejorar la Accuracy
(exactitud) obtenida en la clase anterior. Recuerda también que la
Accuracy no es su ciente, también hay que mirar otras métricas como
por ejemplo`
- `Accuracy, la exactitud de la predicción: (TP+TN)/(TP+TN+FP+FN)`
- `Precision, medida de la precisión del algoritmo para la clase positiva:
TP/(TP+FP)`
- `Recall, medida de la completitud del algoritmo: TP/(TP+FN)`
- `F1 Score, compromiso entre la precisión y la completitud:
2*Precision*Recall/(Precision+Recall)`

`Os recuerdo que TP = #Verdaderos Positivos, TN =#Verdaderos
Negativos, FP = #Falsos Positivos y FN = #Falsos Negativos`

$$ \displaystyle {\begin{bmatrix} TP & FN \\ FP & TN \end{bmatrix}} $$

### KNN

In [5]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
classifier.fit(X_train,y_train)

precision()

Matriz de confusión:
[[81 16]
 [62 41]]

Accuracy: 0.61
Presición: 0.57
Recall: 0.84
F1 Score: 0.68


### Regresión Logística

In [6]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

precision()

Matriz de confusión:
[[76 21]
 [38 65]]

Accuracy: 0.7
Presición: 0.67
Recall: 0.78
F1 Score: 0.72


### Arboles de Clasifición

In [7]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion="entropy",random_state=0)
classifier.fit(X_train,y_train)

precision()

Matriz de confusión:
[[66 31]
 [35 68]]

Accuracy: 0.67
Presición: 0.65
Recall: 0.68
F1 Score: 0.67


### Bosques Aleatorios

In [8]:
from sklearn.ensemble import  RandomForestClassifier 

classifier = RandomForestClassifier(n_estimators=8, criterion="entropy" ,random_state=0)
classifier.fit(X_train,y_train)

precision()

Matriz de confusión:
[[74 23]
 [32 71]]

Accuracy: 0.72
Presición: 0.7
Recall: 0.76
F1 Score: 0.73


### Maquina de Soporte Vectorial (SVM)

In [9]:
from sklearn.svm import SVC

classifier = SVC(kernel="linear", random_state=0)
classifier.fit(X_train,y_train)

precision()

Matriz de confusión:
[[74 23]
 [35 68]]

Accuracy: 0.71
Presición: 0.68
Recall: 0.76
F1 Score: 0.72


#### `Pregunta 3`
`Intenta otros algoritmos de clasificación que no hemos cubierto en la
Parte 3 - Clasificación. Los buenos para NLP incluyen:`
- `CART`
- `C5.0`
- `Máxima Entropía`

In [ ]:
# CART <> Arboles de desición y Regresión (Skity learn usa una versión optimizada del algoritmo CART)
